=== localstorm/hello-world-projects/trunk/DTD-Test/80030.dtd
<!ELEMENT message (comment?,datetime,sender,area*)>
   <!ATTLIST message
   	class   	CDATA #REQUIRED 
   	version 	CDATA #REQUIRED 
   	number 	CDATA #REQUIRED  
   >

<!ELEMENT datetime (timestamp, daylightsavingtime, day)>
<!ELEMENT timestamp (#PCDATA)>
<!ELEMENT daylightsavingtime (#PCDATA)>  
<!ELEMENT day (#PCDATA)>  

<!ELEMENT sender (inn,name)>
<!ELEMENT inn (#PCDATA)>
<!ELEMENT name (#PCDATA)>

<!ELEMENT comment (#PCDATA)>

<!ELEMENT area (inn, name, measuringscheme+, measuringobject+, measuringtool+) >
<!ATTLIST area
	timezone	CDATA #IMPLIED
>

<!ELEMENT measuringscheme (period+) >


<!ELEMENT measuringtool (record+) >
   <!ATTLIST measuringtool
   	code   	CDATA #REQUIRED 
   	name   	CDATA #REQUIRED 
   	type   	CDATA #REQUIRED 
   >

<!ELEMENT record (#PCDATA) >
   <!ATTLIST record
   	type	CDATA #REQUIRED 
   	timestamp CDATA #REQUIRED 
   >


<!ELEMENT measuringobject (period+) >
   <!ATTLIST measuringobject
   	code   	CDATA #REQUIRED 
   	name   	CDATA #REQUIRED 
   	type   	CDATA #REQUIRED 
   >

<!ELEMENT period (value) >
   <!ATTLIST period
   	start 	CDATA #REQUIRED  
   	end 	CDATA #REQUIRED  
   	summer  CDATA #IMPLIED >

<!ELEMENT value (#PCDATA) >
   <!ATTLIST value 
	status	CDATA #IMPLIED  
    >

=== localstorm/hello-world-projects/trunk/DTD-Test/input.80030.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE message SYSTEM "80030.dtd">

<message class="80030" version="1" number="22">
    <datetime>
	<timestamp>20031103144121</timestamp>
	<daylightsavingtime>0</daylightsavingtime>
	<day>20031102</day>
    </datetime>

    <sender>
	<inn>4401003493</inn>
	<name>Костромская ГРЭС</name>
    </sender>

    <area>

        <inn>4401003493</inn>
	<name>Костромская ГРЭС</name>
    
        <measuringscheme>
	    <period start="0000" end="1230"><value>1</value></period>
    	    <period start="1230" end="0000"><value>2</value></period>
	</measuringscheme>

	<measuringobject code="423430001123405" name="ШСВ" type="1">
    	    <period start="0000" end="1230"><value>0</value></period>
	    <period start="1230" end="0000"><value>1</value></period>
	</measuringobject>

	<measuringtool code="13141507867512301" name="счетчик" type="1">
	    <record type="0300" timestamp="20031014000045">пропадание питания</record>
    	    <record type="0301" timestamp="20031014000230">восстановление питания</record>
	</measuringtool>

    </area>
</message>
